Products
Vlad-Kozak/Team-A pull request #11
Opened 2022-04-23 17:10 UTC by Vadym-Vasiliev

2022-04-23 18:05 UTC, Vlad-Kozak requested changes
1 убрать минусовый маржин у списка, и сделать правый маржин айтемов (кроме последнего)
2 ширину айтемов сделать "100% разделить на  3 минус два маржина (между айтемами)"
3 устранить все пробелмы которые вылезут

2022-04-24 05:36 UTC, Vadym-Vasiliev commented
забрав мінусовий  маржин
зробив правильну формулу на лішки 
виправив всі проблеми які вилізли

2022-04-24 07:18 UTC, Vlad-Kozak reviewed
все хорошо, только в таблете текст с ошибкой, написал 198 без пикселей

2022-04-24 12:01 UTC, Vadym-Vasiliev commented
додав px

2022-04-24 12:05 UTC, Vlad-Kozak approved these changes

2022-04-24 12:05 UTC, merged